---
title: "Longitudinal Data Analysis Assignment 2"
author: "Andomei Smit: SMTAND051"
date: "01/09/2025"
output:
  bookdown::pdf_document2:
    toc: true
    toc_depth: 2
    fig_caption: true
    keep_tex: true
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
library(nlme)
library(faraway)
library(lattice)
library(dplyr)
library(ggplot2)
library(tidyr)
library(MuMIn)
```

# Introduction

```{r}
# read in the data
malaria <- read.csv("malariadata.csv")
#head(malaria)

# random sample carefully so that records stay complete
set.seed(1997)
# sample 75% of unique pids
sampled_pids <- malaria %>%
  distinct(pid) %>%
  slice_sample(prop = 0.75) %>%
  pull(pid)

# keep all rows for those pids
malaria <- malaria %>% semi_join(tibble(pid = sampled_pids), by = "pid")

# order malaria by pid
malaria <- malaria[order(malaria$pid, malaria$pday),]
rm(sampled_pids)
```

# Data Cleaning

```{r}
unique(malaria$Studyyear) # all 2003, can drop it!
unique(malaria$country) # all Mozambique, so can drop it!

# remove Studyyear, country, Hb, pardens, gamedens, PIoutcome, PIoutcomeday
malaria <- malaria %>% select(-c(Studyyear, country, Hb, pardens, gamedens, PIoutcome, PIoutcomeday))

# what columns are left
colnames(malaria)

# how many subjects per site?
malaria %>%
  distinct(pid, site) %>%     # ensure one row per subject–site
  count(site, name = "n_subjects")

# collapse the sites to north and south regions
malaria <- malaria %>%
  mutate(region = case_when(
    site %in% c("Namaacha","Catuane","Boane") ~ "South",
    site == "Magude" ~ "North",
    TRUE ~ as.character(site)   # fallback in case of other sites
  ))
# drop site
malaria <- malaria %>% select(-site)

# missing values in responses: 
colSums(is.na(malaria))

# create two datasets for each drug (remove all NA rows of that drug):
pyr_df  <- subset(malaria, !is.na(Pyrconcentration))
sulf_df <- subset(malaria, !is.na(Sulfconcentration))


# remove patients who have an increase in drug concentration after day 3
pyr_bad_ids <- pyr_df %>%
  filter(pday > 3) %>%
  group_by(pid) %>%
  arrange(pday) %>%
  summarise(any_increase = any(diff(Pyrconcentration) > 0, na.rm = TRUE)) %>%
  filter(any_increase) %>%
  pull(pid)

# Drop those patients
pyr_df <- pyr_df %>%
  filter(!pid %in% pyr_bad_ids)

# repeat for sulf
sulf_bad_ids <- sulf_df %>%
  filter(pday > 3) %>%
  group_by(pid) %>%
  arrange(pday) %>%
  summarise(any_increase = any(diff(Sulfconcentration) > 0, na.rm = TRUE)) %>%
  filter(any_increase) %>%
  pull(pid)

# Drop those patients
sulf_df <- sulf_df %>%
  filter(!pid %in% sulf_bad_ids)

# create grouped data:
pyr_gd <- groupedData(Pyrconcentration ~ pday | pid,
                      data  = pyr_df,
                      outer = ~ arm)

sulf_gd <- groupedData(Sulfconcentration ~ pday | pid,
                       data  = sulf_df,
                       outer = ~ arm)

# create correct data types, center and scale covariates
for(df in c("pyr_df","sulf_df")){
  tmp <- get(df)
  tmp$pid    <- factor(tmp$pid)
  tmp$arm    <- factor(tmp$arm)           # consider setting baseline level = "SP"
  tmp$gender <- factor(tmp$gender)
  tmp$region <- factor(tmp$region)
  tmp$pday   <- as.numeric(tmp$pday)

  # center/scale continuous covariates (optional but helpful)
  tmp$c_weight <- scale(tmp$weight, center=TRUE, scale=FALSE)
  tmp$c_age    <- scale(tmp$age,    center=TRUE, scale=FALSE)

  assign(df, tmp)
}
```

# EDA

## Correlation checks

```{r}
# correlation between age and weight
cor(pyr_df$age, pyr_df$weight, use="complete.obs") # very high
cor(sulf_df$age, sulf_df$weight, use="complete.obs") # very high
```

## Specific questions

```{r}
# number of patients within each dataset
length(unique(pyr_df$pid)) # 245
length(unique(sulf_df$pid)) # 259
length(unique(malaria$pid)) # 306
```

```{r}
# are age and weight constant within patient?
df_age_weight <- malaria %>%
  group_by(pid) %>%
  summarise(
    n_age = n_distinct(age),
    n_weight = n_distinct(weight)
  ) %>%
  # filter for only records where either age or weight has > 1 distinct values
  filter(n_age > 1 | n_weight > 1)
# empty data frame, thus age and weight are constant within patient
rm(df_age_weight)
```

## Distribution of continuous covariates between regions and arm

```{r}
# begin by summarising the data at pid level
# Subject-level reductions
subjects <- malaria %>%
  arrange(pid, pday) %>%
  group_by(pid) %>%
  summarise(
    arm     = dplyr::first(na.omit(arm)),
    region  = dplyr::first(na.omit(region)),
    gender  = dplyr::first(na.omit(gender)),
    age     = dplyr::first(na.omit(age)),  
    weight  = dplyr::first(na.omit(weight)),
    .groups = "drop"
  )
```

```{r}
# summarise age by region and arm
var_to_plot <- "age"

# Boxplots/violin by arm within each region
p_age <- ggplot(subjects, aes(x = arm, y = .data[[var_to_plot]], fill = arm)) +
  geom_violin(trim = FALSE, alpha = 0.25, na.rm = TRUE, color = NA) +
  geom_boxplot(width = 0.2, outlier.shape = 21, na.rm = TRUE) +
  facet_wrap(~ region, scales = "fixed") +
  labs(x = "Arm", y = var_to_plot, title = paste("Distribution of", var_to_plot, "by Arm within Region")) +
  theme_bw() + theme(legend.position = "none")

ggsave("plots/age_dbn.pdf", plot = p_age, width = 5, height = 3)
```

```{r}
var_to_plot <- "weight"

# Boxplots/violin by arm within each region
p_weight <- ggplot(subjects, aes(x = arm, y = .data[[var_to_plot]], fill = arm)) +
  geom_violin(trim = FALSE, alpha = 0.25, na.rm = TRUE, color = NA) +
  geom_boxplot(width = 0.2, outlier.shape = 21, na.rm = TRUE) +
  facet_wrap(~ region, scales = "fixed") +
  labs(x = "Arm", y = var_to_plot, title = paste("Distribution of", var_to_plot, "by Arm within Region")) +
  theme_bw() + theme(legend.position = "none")

ggsave("plots/weight_dbn.pdf", plot = p_weight, width = 5, height = 3)
```

## Dropout rate: pyr

```{r}
# time on study/ dropout pattern
last_obs_pyr <- malaria %>%
  filter(!is.na(Pyrconcentration)) %>%                 # only rows where Pyr is observed
  group_by(pid) %>%
  summarise(
    last_pday = max(pday),               # last day observed for that pid
    n_obs     = n(),                     # how many Pyr measurements they have
    .groups = "drop"
  )

subjects <- malaria %>% distinct(pid, arm, region)

# counts of last observed day by arm
last_by_arm_pyr <- last_obs_pyr %>%
  left_join(subjects, by = "pid") %>%
  count(arm, last_pday, name = "n_subjects") %>%
  tidyr::pivot_wider(names_from = arm, values_from = n_subjects, values_fill = 0)

unique_days <- sort(unique(malaria$pday))

retention <- dplyr::bind_rows(lapply(unique_days, function(d) {
  last_obs_pyr %>%
    left_join(subjects, by = "pid") %>%
    group_by(arm) %>%
    summarise(n_at_least_d = sum(!is.na(last_pday) & last_pday >= d), .groups = "drop") %>%
    mutate(pday = d)
}))


p_ret_pyr <- ggplot(retention, aes(x = pday, y = n_at_least_d, color = arm)) +
   geom_line(linewidth = 1) + 
  geom_point() +
   labs(y = "Subjects with observed ≥ day", title = "Retention over time by Arm (Pyrimethamine)")+
  theme_bw()
ggsave("plots/retention_arm_pyr.pdf", plot = p_ret_pyr, height = 3, width = 5)
```


```{r}
# retention by region
last_obs <- malaria %>%
  filter(!is.na(Pyrconcentration)) %>%
  group_by(pid) %>%
  summarise(last_pday = max(pday), .groups = "drop")

# attach region info
subjects <- malaria %>% distinct(pid, region)
last_obs <- left_join(last_obs, subjects, by = "pid")

unique_days <- sort(unique(malaria$pday))

retention_region <- bind_rows(lapply(unique_days, function(d) {
  last_obs %>%
    group_by(region) %>%
    summarise(
      n_at_least_d = sum(!is.na(last_pday) & last_pday >= d),
      .groups = "drop"
    ) %>%
    mutate(pday = d)
}))

p_ret_reg <- ggplot(retention_region, aes(x = pday, y = n_at_least_d, color = region)) +
  geom_line(linewidth = 1) +
  geom_point() +
  labs(
    x = "Day",
    y = "Subjects with observed ≥ day",
    title = "Retention over time by Region (Pyrimethamine)"
  ) +
  theme_bw()
ggsave("plots/retention_region_pyr.pdf", plot = p_ret_reg, width = 5, height = 3)
```


## Dropout rate: sulf

```{r}
# time on study/ dropout pattern
last_obs_sulf <- malaria %>%
  filter(!is.na(Sulfconcentration)) %>%                 # only rows where Sulf is observed
  group_by(pid) %>%
  summarise(
    last_pday = max(pday),               # last day observed for that pid
    n_obs     = n(),                     # how many Sulf measurements they have
    .groups = "drop"
  )

subjects <- malaria %>% distinct(pid, arm, region)

# counts of last observed day by arm
last_by_arm_sulf <- last_obs_sulf %>%
  left_join(subjects, by = "pid") %>%
  count(arm, last_pday, name = "n_subjects") %>%
  tidyr::pivot_wider(names_from = arm, values_from = n_subjects, values_fill = 0)

unique_days <- sort(unique(malaria$pday))

retention <- dplyr::bind_rows(lapply(unique_days, function(d) {
  last_obs_sulf %>%
    left_join(subjects, by = "pid") %>%
    group_by(arm) %>%
    summarise(n_at_least_d = sum(!is.na(last_pday) & last_pday >= d), .groups = "drop") %>%
    mutate(pday = d)
}))


p_ret_sulf <- ggplot(retention, aes(x = pday, y = n_at_least_d, color = arm)) +
   geom_line(linewidth = 1) + 
  geom_point() +
   labs(y = "Subjects with observed ≥ day", title = "Retention over time by Arm (Sulfadoxine)")+
  theme_bw()
ggsave("plots/retention_arm_sulf.pdf", plot = p_ret_pyr, height = 3, width = 5)
```


```{r}
# retention by region
last_obs <- malaria %>%
  filter(!is.na(Sulfconcentration)) %>%
  group_by(pid) %>%
  summarise(last_pday = max(pday), .groups = "drop")

# attach region info
subjects <- malaria %>% distinct(pid, region)
last_obs <- left_join(last_obs, subjects, by = "pid")

unique_days <- sort(unique(malaria$pday))

retention_region <- bind_rows(lapply(unique_days, function(d) {
  last_obs %>%
    group_by(region) %>%
    summarise(
      n_at_least_d = sum(!is.na(last_pday) & last_pday >= d),
      .groups = "drop"
    ) %>%
    mutate(pday = d)
}))

p_ret_reg <- ggplot(retention_region, aes(x = pday, y = n_at_least_d, color = region)) +
  geom_line(linewidth = 1) +
  geom_point() +
  labs(
    x = "Day",
    y = "Subjects with observed ≥ day",
    title = "Retention over time by Region (Sulfadoxine)"
  ) +
  theme_bw()
ggsave("plots/retention_region_sulf.pdf", plot = p_ret_reg, width = 5, height = 3)
```

## Pyr dataset questions

```{r}
# gender: are the males and females balanced?
pyr_df %>%
  distinct(pid, gender) %>%   
  filter(gender == "F") %>%
  summarise(n_females = n())
# 156 of 245, roughly 64%
```

```{r}
# arm: are the treatments balanced?
pyr_df %>%
  distinct(pid, arm) %>%   
  filter(arm == "SP") %>%
  summarise(n_SP = n())
# 119 out of 245 is SP, thus roughly balanced according to treatment
```

```{r}
# do both regions offer both treatments?
pyr_df %>%
  group_by(region, arm) %>%
  summarise(n_unique_pid = n_distinct(pid), .groups = "drop")
# roughly balanced between regions
```

## Sulf dataset questions

```{r}
# gender: are the males and females balanced?
sulf_df %>%
  distinct(pid, gender) %>%   
  filter(gender == "F") %>%
  summarise(n_females = n())
# 157 of 259, roughly 60%
```

```{r}
# arm: are the treatments balanced?
sulf_df %>%
  distinct(pid, arm) %>%   
  filter(arm == "SP") %>%
  summarise(n_SP = n())
# 130 out of 259 is SP, thus roughly balanced according to treatment
```

```{r}
# do both regions offer both treatments?
sulf_df %>%
  group_by(region, arm) %>%
  summarise(n_unique_pid = n_distinct(pid), .groups = "drop")
# roughly balanced between regions
```

## Subject profiles

```{r}
## plot scatterplot of drug concentrations:
pyr_df$arm <- as.factor(pyr_df$arm)
sulf_df$arm <- as.factor(sulf_df$arm)

#pdf("plots/scatter_drug_time.pdf", height = 4, width = 7)
#op <- par(mfrow = c(1,2))
#with(pyr_df,  plot(pday, Pyrconcentration,  pch = 16, cex = .6, col = as.integer(arm),
#                   main = "Pyrimethamine (raw)", xlab = "Day", ylab = #"Concentration"))
#legend("topright", legend = levels(pyr_df$arm), pch = 16, col = #seq_along(levels(pyr_df$arm)), bty = "n")

#with(sulf_df, plot(pday, Sulfconcentration, pch = 16, cex = .6, col = as.integer(arm),
#                   main = "Sulfadoxine (raw)", xlab = "Day", ylab = "Concentration"))
#legend("topright", legend = levels(sulf_df$arm), pch = 16, col = seq_along(levels(sulf_df$arm)), bty = "n")
#par(op)
#dev.off()

## plot spaghetti plots of drug concentrations:
# Pyrimethamine
g_pyr <- ggplot(pyr_df, aes(pday, Pyrconcentration, group = pid, colour = arm)) +
  geom_line(alpha = 0.25, linewidth = 0.4) +
  facet_wrap(~ arm, nrow = 1) +
  labs(title = "Pyrimethamine concentration on the original scale",
       x = "Day", y = "Concentration") +
  theme_minimal() + 
  theme(legend.position = "none")
ggsave("plots/pyr_time.pdf", plot = g_pyr, width = 6, height = 3)

# Sulfadoxine
g_sulf <- ggplot(sulf_df, aes(pday, Sulfconcentration, group = pid, colour = arm)) +
  geom_line(alpha = 0.25, linewidth = 0.4) +
  facet_wrap(~ arm, nrow = 1) +
  labs(title = "Sulfadoxine concentration on the original scale",
       x = "Day", y = "Concentration") +
  theme_minimal() + 
  theme(legend.position = "none")
ggsave("plots/sulf_time.pdf", plot = g_sulf, width = 6, height = 3)
```

```{r}
rm(g_pyr)
rm(g_sulf)
rm(last_by_arm_pyr)
rm(last_by_arm_sulf)
rm(last_obs)
rm(last_obs_pyr)
rm(last_obs_sulf)
rm(p_age)
rm(p_ret_pyr)
rm(p_ret_reg)
rm(p_ret_sulf)
rm(p_weight)
rm(retention)
rm(retention_region)
rm(subjects)
rm(tmp)
rm(df)
rm(pyr_bad_ids)
rm(sulf_bad_ids)
rm(unique_days)
rm(var_to_plot)
```


# Model fitting: Pyr

```{r}
#  since we don't have a dose, we can just make the dose the same for everyone
pyr_df$Dose_Pyr <- 1 
pyr_gd <- groupedData(Pyrconcentration ~ pday | pid, data = pyr_df)

pyr_nls <- nlsList(
  Pyrconcentration ~ SSfol(Dose_Pyr, pday, lKe, lKa, lCl),
  data     = pyr_gd,
  na.action = na.omit,
  control  = nls.control(maxiter = 100, warnOnly = TRUE)
)

summary(pyr_nls)      # per-patient fit summaries, lots of NA!

plot(intervals(pyr_nls))
```

What if we try to keep only pid's whose estimates were not NA?

```{r}
coef_nls <- try(coef(pyr_nls), silent = TRUE)
ok <- rowSums(is.na(coef_nls)) == 0  # subjects with all 3 params
good_pids <- rownames(coef_nls)[ok]

length(good_pids)          # how many “good” subjects: 58

# now refit it with only these people:
pyr_gd_good <- groupedData(Pyrconcentration ~ pday | pid,
                           data = subset(pyr_df, pid %in% good_pids))

pyr_nls_good <- nlsList(
  Pyrconcentration ~ SSfol(Dose_Pyr, pday, lKe, lKa, lCl),
  data      = pyr_gd_good,
  na.action = na.omit,
  control   = nls.control(maxiter = 100, warnOnly = TRUE)
)
summary(pyr_nls_good)

plot(intervals(pyr_nls_good))
intervals(pyr_nls_good)
# MOM2004-187 looks bad- remove!

```

Retry fitting nlme

```{r}
try_1000 <- nlme(
  pyr_nls_good,
  control = nlmeControl(
    pnlsTol = 0.1,    # looser PNLS tolerance often helps early iterations
    msMaxIter = 300,  # mixed step iterations
    msVerbose = TRUE  # print progress to see if it’s getting better
  )
)

summary(try_1000)

try_10000 <- nlme(
  pyr_nls,                       # nlsList object
  ## keep it simple early on
  random  = pdDiag(lKe + lKa ~ 1),
  method  = "REML"
)

# running lKa, lCl and lKe did not converge
# removing lKa lead to singularities
# removing lCl lead to immediate convergence
# removing lKe still did not converge

summary(try_10000)
```

























Why did so many fail?

```{r}
## 1) Get per-subject starting values where available
pyr_nls <- nlsList(
  Pyrconcentration ~ SSfol(Dose_Pyr, pday, lKe, lKa, lCl),
  data = pyr_gd,
  na.action = na.omit,
  control = nls.control(maxiter = 100, warnOnly = TRUE)
)

coef_nls <- try(coef(pyr_nls), silent = TRUE)

## 2) Robust population starts from successful subjects
good_mat <- coef_nls[complete.cases(coef_nls), , drop = FALSE]
pop_start <- apply(good_mat, 2, median, na.rm = TRUE)  # c(lKe=..., lKa=..., lCl=...)

## 3) Mixed-effects on ALL subjects using those fixed-effect starts
##    (Diagonal random effects often helps early stability.)
try_full <- nlme(
  fixed = lKe + lKa + lCl ~ 1,
  data  = pyr_gd,  # <- ALL subjects
  random = lKe + lKa +lCl~1,
  start = as.numeric(pop_start),
  ## selfStart model as a 'model' argument:
  model = Pyrconcentration ~ SSfol(Dose_Pyr, pday, lKe, lKa, lCl),
  na.action = na.omit,
  control = nlmeControl(
    pnlsTol   = 0.1,
    msMaxIter = 300,
    msVerbose = TRUE
  )
)

summary(try_full)
intervals(try_full)

df_all <- as.data.frame(pyr_gd)
df_all$lKa_fixed <- pop_start["lKa"]

## Fix lKa at the median and estimate random effects for lKe and lCl only
try_full_fixKa <- nlme(
  model  = Pyrconcentration ~ SSfol(Dose_Pyr, pday, lKe, lKa_fixed, lCl),
  data   = df_all,
  fixed  = lKe + lCl ~ 1,
  random = lKe + lCl ~ 1 | pid,    # diagonal Σ_b
  groups = ~ pid,                   # <- grouping goes here with pdMat
  start  = c(lKe = pop_start["lKe"], lCl = pop_start["lCl"]),
  control = nlmeControl(pnlsTol = 0.1, msMaxIter = 300, msVerbose = TRUE)
)


```

